In [34]:
import pandas as pd

a = {'Albums': ['Thriller', 'Back in Black', 'Dark Side of the Moon', 'The Body Guard', 'Bat Out of Hell'], \
    'Length': ['00:42:19','00:42:11', '00:42:49', '00:57:44', '00:46:33'], \
    'Released':['1982', '1980','1973', '1992', '1977']}
df= pd.DataFrame(a)
df

                  Albums    Length Released
0               Thriller  00:42:19     1982
1          Back in Black  00:42:11     1980
2  Dark Side of the Moon  00:42:49     1973
3         The Body Guard  00:57:44     1992
4        Bat Out of Hell  00:46:33     1977

In [35]:
df.dtypes

Albums      object
Length      object
Released    object
dtype: object

In [36]:
df['Albums']

0                 Thriller
1            Back in Black
2    Dark Side of the Moon
3           The Body Guard
4          Bat Out of Hell
Name: Albums, dtype: object

In [37]:
df.Albums

0                 Thriller
1            Back in Black
2    Dark Side of the Moon
3           The Body Guard
4          Bat Out of Hell
Name: Albums, dtype: object

In [38]:
df[:2]

          Albums    Length Released
0       Thriller  00:42:19     1982
1  Back in Black  00:42:11     1980

In [39]:
df['Albums'][1:4]

1            Back in Black
2    Dark Side of the Moon
3           The Body Guard
Name: Albums, dtype: object

In [40]:
df.head(3)

                  Albums    Length Released
0               Thriller  00:42:19     1982
1          Back in Black  00:42:11     1980
2  Dark Side of the Moon  00:42:49     1973

In [41]:
df['SoundTrack'] = df.Albums == 'The Body Guard'
df

                  Albums    Length Released  SoundTrack
0               Thriller  00:42:19     1982       False
1          Back in Black  00:42:11     1980       False
2  Dark Side of the Moon  00:42:49     1973       False
3         The Body Guard  00:57:44     1992        True
4        Bat Out of Hell  00:46:33     1977       False

In [60]:
df.loc[0]

Albums        Thriller
Length        00:42:19
Released          1982
SoundTrack           0
Name: 0, dtype: object

In [33]:
del df['SoundTrack']
df

                  Albums    Length Released
0               Thriller  00:42:19     1982
1          Back in Black  00:42:11     1980
2  Dark Side of the Moon  00:42:49     1973
3         The Body Guard  00:57:44     1992
4        Bat Out of Hell  00:46:33     1977

In [67]:
df.drop('Length', axis=1, inplace = True)

In [68]:
df

                               Albums Released  SoundTrack
0                            Thriller     1982           0
1                       Back in Black     1980           0
2               Dark Side of the Moon     1973           0
3                      The Body Guard     1992           1
4                     Bat Out of Hell     1977           0
The Body Guard                     10       10          10

In [109]:
df_can1 = pd.read_excel('Canada.xlsx', sheet_name ='Canada by Citizenship',  skip_footer = 2)
print('Data read into a pandas Dataframe!')

Data read into a pandas Dataframe!

In [110]:
df_can1

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
5,Immigrants,Foreigners,Angola,903,Africa,911,Middle Africa,902,Developing regions,1,...,268,295,184,106,76,62,61,39,70,45
6,Immigrants,Foreigners,Antigua and Barbuda,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,0,...,14,24,32,15,32,38,27,37,51,25
7,Immigrants,Foreigners,Argentina,904,Latin America and the Caribbean,931,South America,902,Developing regions,368,...,1591,1153,847,620,540,467,459,278,263,282
8,Immigrants,Foreigners,Armenia,935,Asia,922,Western Asia,902,Developing regions,0,...,147,224,218,198,205,267,252,236,258,207
9,Immigrants,Foreigners,Australia,909,Oceania,927,Australia and New Zealand,901,Developed regions,702,...,930,909,875,1033,1018,1018,933,851,982,1121
10,Immigrants,Foreigners,Austria,908,Europe,926,Western Europe,901,Developed regions,234,...,118,122,102,98,91,109,124,84,102,90
11,Immigrants,Foreigners,Azerbaijan,935,Asia,922,Western Asia,902,Developing regions,0,...,230,359,236,203,125,165,209,138,161,57
12,Immigrants,Foreigners,Bahamas,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,26,...,13,14,18,23,30,27,25,40,60,55
13,Immigrants,Foreigners,Bahrain,935,Asia,922,Western Asia,902,Developing regions,0,...,12,12,12,22,9,35,28,21,39,32
14,Immigrants,Foreigners,Bangladesh,935,Asia,5501,Southern Asia,902,Developing regions,83,...,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789
15,Immigrants,Foreigners,Barbados,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,372,...,90,111,97,130,134,125,121,97,132,97
16,Immigrants,Foreigners,Belarus,908,Europe,923,Eastern Europe,901,Developed regions,0,...,543,558,439,568,524,454,438,357,277,247
17,Immigrants,Foreigners,Belgium,908,Europe,926,Western Europe,901,Developed regions,511,...,411,400,302,363,335,358,363,332,402,379
18,Immigrants,Foreigners,Belize,904,Latin America and the Caribbean,916,Central America,902,Developing regions,16,...,25,37,24,28,48,38,39,36,34,53
19,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,112,95,116,183,205,238,290,284,391,397
20,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487
21,Immigrants,Foreigners,Bolivia (Plurinational State of),904,Latin America and the Caribbean,931,South America,902,Developing regions,44,...,85,134,139,107,143,214,180,86,83,107
22,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
23,Immigrants,Foreigners,Botswana,903,Africa,913,Southern Africa,902,Developing regions,10,...,9,7,11,8,28,15,42,53,64,76
24,Immigrants,Foreigners,Brazil,904,Latin America and the Caribbean,931,South America,902,Developing regions,211,...,917,969,1181,1746,2138,2509,2598,1508,1642,1714
25,Immigrants,Foreigners,Brunei Darussalam,935,Asia,920,South-Eastern Asia,902,Developing regions,79,...,3,4,5,11,10,5,12,6,3,6
26,Immigrants,Foreigners,Bulgaria,908,Europe,923,Eastern Europe,901,Developed regions,24,...,2022,1738,1419,1172,994,784,556,365,451,512
27,Immigrants,Foreigners,Burkina Faso,903,Africa,914,Western Africa,902,Developing regions,2,...,97,91,147,136,139,162,186,144,269,322
28,Immigrants,Foreigners,Burundi,903,Africa,910,Eastern Africa,902,Developing regions,0,...,559,626,468,614,448,566,529,604,684,480
29,Immigrants,Foreigners,Cabo Verde,903,Africa,914,Western Africa,902,Developing regions,1,...,3,5,7,2,5,1,3,3,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Immigrants,Foreigners,Suriname,904,Latin America and the Caribbean,931,South America,902,Developing regions,15,...,17,15,16,20,9,12,13,11,16,4
166,Immigrants,Foreigners,Swaziland,903,Africa,913,Southern Africa,902,Developing regions,4,...,8,7,7,5,6,10,3,13,17,39
167,Immigrants,Foreigners,Sweden,908,Europe,924,Northern Europe,901,Developed regions,281,...,129,205,139,193,165,167,159,134,140,140
168,Immigrants,Foreigners,Switzerland,908,Europe,926,Western Europe,901,Developed regions,806,...,337,270,258,308,357,328,285,266,243,201
169,Immigrants,Foreigners,Syrian Arab Republic,935,Asia,922,Western Asia,902,Developing regions,315,...,1116,1458,1145,1056,919,917,1039,1005,650,1009
170,Immigrants,Foreigners,Tajikistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,14,85,46,44,15,50,52,47,34,39
171,Immigrants,Foreigners,Thailand,935,Asia,920,South-Eastern Asia,902,Developing regions,56,...,392,575,500,487,519,512,499,396,296,400
172,Immigrants,Foreigners,The former Yugoslav Republic of Macedonia,908,Europe,925,Southern Europe,901,Developed regions,0,...,443,285,256,211,191,198,188,130,126,112
173,Immigrants,Foreigners,Togo,903,Africa,914,Western Africa,902,Developing regions,5,...,163,157,149,235,351,400,354,261,299,316
174,Immigrants,Foreigners,Tonga,909,Oceania,957,Polynesia,902,Developing regions,2,...,5,2,0,1,0,5,5,2,3,5
175,Immigrants,Foreigners,Trinidad and Tobago,904,Latin America and the Caribbean,915,Caribbean,902,Developing regions,958,...,730,857,794,975,1002,1134,915,588,586,427
176,Immigrants,Foreigners,Tunisia,903,Africa,912,Northern Africa,902,Developing regions,58,...,764,756,1065,869,950,1195,1299,1442,1503,1627
177,Immigrants,Foreigners,Turkey,935,Asia,922,Western Asia,902,Developing regions,481,...,1736,2065,1638,1463,1122,1238,1492,1257,1068,729
178,Immigrants,Foreigners,Turkmenistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,16,40,26,37,13,20,30,20,20,14
179,Immigrants,Foreigners,Tuvalu,909,Oceania,957,Polynesia,902,Developing regions,0,...,2,0,0,1,0,0,0,1,0,0
180,Immigrants,Foreigners,Uganda,903,Africa,910,Eastern Africa,902,Developing regions,13,...,160,239,201,170,204,185,216,213,222,206
181,Immigrants,Foreigners,Ukraine,908,Europe,923,Eastern Europe,901,Developed regions,0,...,2431,2270,1973,2218,1937,2367,3159,2515,2265,2487
182,Immigrants,Foreigners,United Arab Emirates,935,Asia,922,Western Asia,902,Developing regions,0,...,41,31,42,37,33,37,86,60,54,46
183,Immigrants,Foreigners,United Kingdom of Great Britain and Northern I...,908,Europe,924,Northern Europe,901,Developed regions,22045,...,7533,7258,7140,8216,8979,8876,8724,6204,6195,5827
184,Immigrants,Foreigners,United Republic of Tanzania,903,Africa,910,Eastern Africa,902,Developing regions,635,...,310,274,291,195,230,136,200,215,224,182
185,Immigrants,Foreigners,United States of America,905,Northern America,905,Northern America,901,Developed regions,9378,...,6990,8394,9613,9463,10190,8995,8142,7676,7891,8501
186,Immigrants,Foreigners,Uruguay,904,Latin America and the Caribbean,931,South America,902,Developing regions,128,...,130,217,175,147,160,99,93,81,47,58
187,Immigrants,Foreigners,Uzbekistan,935,Asia,5500,Central Asia,902,Developing regions,0,...,175,330,262,284,215,288,289,162,235,167
188,Immigrants,Foreigners,Vanuatu,909,Oceania,928,Melanesia,902,Developing regions,0,...,1,1,1,0,0,1,0,0,0,0
189,Immigrants,Foreigners,Venezuela (Bolivarian Republic of),904,Latin America and the Caribbean,931,South America,902,Developing regions,103,...,1224,1211,1192,1335,1239,1353,998,1452,1373,1022
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [111]:
df_can1.drop(['AREA', 'REG', 'DEV'],axis=1,inplace=True)
df_can1.head()

,Type,Coverage,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [114]:
df_can1.rename(columns = {'OdName': 'Country', 'AreaName': 'Continent', 'RegName': 'Region'},inplace = True)
df_can1.columns

Index([     'Type',  'Coverage',   'Country', 'Continent',    'Region',
         'DevName',        1980,        1981,        1982,        1983,
              1984,        1985,        1986,        1987,        1988,
              1989,        1990,        1991,        1992,        1993,
              1994,        1995,        1996,        1997,        1998,
              1999,        2000,        2001,        2002,        2003,
              2004,        2005,        2006,        2007,        2008,
              2009,        2010,        2011,        2012,        2013],
      dtype='object')

In [115]:
df_can1['Total'] = df_can1.sum(axis=1)

In [116]:
df_can1.head()

,Type,Coverage,Country,Continent,Region,DevName,1980,1981,1982,1983,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Immigrants,Foreigners,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Immigrants,Foreigners,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Immigrants,Foreigners,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,Immigrants,Foreigners,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Immigrants,Foreigners,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [120]:
df_can1.loc['Total1'] = df_can1.sum(axis=0)

In [122]:
df_can1.tail()

,Type,Coverage,Country,Continent,Region,DevName,1980,1981,1982,1983,...,2006,2007,2008,2009,2010,2011,2012,2013,Total,Total1
191,Immigrants,Foreigners,Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,...,1,0,0,0,0,0,0,0,2,NaN
192,Immigrants,Foreigners,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,...,140,122,133,128,211,160,174,217,2985,NaN
193,Immigrants,Foreigners,Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,...,77,71,64,60,102,69,46,59,1677,NaN
194,Immigrants,Foreigners,Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,...,454,663,611,508,494,434,437,407,8598,NaN
Total1,ImmigrantsImmigrantsImmigrantsImmigrantsImmigr...,ForeignersForeignersForeignersForeignersForeig...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,AsiaEuropeAfricaOceaniaEuropeAfricaLatin Ameri...,Southern AsiaSouthern EuropeNorthern AfricaPol...,Developing regionsDeveloped regionsDeveloping ...,99137,110563,104271,75550,...,247057,232405,243047,248768,276956,246194,256222,257537,6409153,0